- apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualenv
    - postgresql
    - postgresql-server-dev-all
    - build-essential
    - libpython-dev
    - libzmq3-dev
    - python-psycopg2
    - supervisor

- user:
    name: rootio

- postgresql_user:
    name: rootio
  become: true
  become_user: postgres

- postgresql_db:
    name: rootio_web
    owner: rootio
  become: true
  become_user: postgres

- git:
    repo: https://github.com/rootio/rootio_web
    dest: /opt/rootio/rootio_web

- pip:
    virtualenv: /opt/rootio/venvs/rootio_web
    requirements: /opt/rootio/rootio_web/requirements.txt

- file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/rootio/rootio_web/instance
    - /opt/rootio/bin

- file:
    path: "{{ item }}"
    state: directory
    owner: rootio
  with_items:
    - /opt/rootio/rootio_web/instance/log
    - /opt/rootio/content

- template:
    src: rootio.cfg
    dest: /opt/rootio/rootio_web/instance/rootio.cfg

- template:
    src: config.py
    dest: /opt/rootio/rootio_web/rootio/config.py

- copy:
    src: bin/rootio_web
    dest: /opt/rootio/bin/rootio_web
    mode: 0755

- copy:
    src: supervisor/rootio_web.conf
    dest: /etc/supervisor/conf.d/rootio_web.conf
