- apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualenv
    - postgresql
    - postgresql-server-dev-all
    - build-essential
    - libpython-dev
    - libzmq3-dev
    - python-psycopg2
    - supervisor
    - nginx

- user:
    name: rootio

- postgresql_user:
    name: rootio
  become: true
  become_user: postgres

- postgresql_db:
    name: rootio
    owner: rootio
  become: true
  become_user: postgres

- import_tasks: tasks/rootio_web.yml

- import_tasks: tasks/station_telephony.yml
