- git:
    repo: https://github.com/rootio/rootio_web
    dest: /opt/rootio/rootio_web
    version: ansible

- pip:
    virtualenv: /opt/rootio/venvs/rootio_web
    requirements: /opt/rootio/rootio_web/requirements.txt

- file:
    path: "{{ item }}"
    state: directory
    owner: rootio
  with_items:
    - /opt/rootio/rootio_web/instance
    - /opt/rootio/rootio_web/instance/log

- template:
    src: rootio_web/rootio.cfg
    dest: /opt/rootio/rootio_web/instance/rootio.cfg

- template:
    src: rootio_web/config.py
    dest: /opt/rootio/rootio_web/rootio/config.py

- copy:
    src: bin/rootio_web
    dest: /opt/rootio/bin/rootio_web
    mode: 0755

- copy:
    src: supervisor/rootio_web.conf
    dest: /etc/supervisor/conf.d/rootio_web.conf

- template:
    src: nginx/rootio_web.conf
    dest: /etc/nginx/sites-enabled/rootio_web.conf
